name: Actions workflow

on:
    push:
        branches:
            - 'feature/*'
            - 'bug/*'
            - '!main'
            - '!develop'

jobs:
    run_github_actions:
        runs-on: ubuntu-latest
        steps:
            - name: github push message
              run: echo 'successful push to github'
