name: Protect Branches

on:
  push:
    branches:
      - main
      - develop

jobs:
  prevent_push:
    runs-on: ubuntu-latest
    steps:
      - name: Fail if pushing directly to protected branches
        run: |
          echo "You cannot push directly to the 'main' or 'develop' branches. Please create a separate branch and submit a pull request."
          exit 1