name: Actions workflow

on:
  push:
    branches:
      - develop
      - main

jobs:
  run_github_actions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: GitHub push message
        run: echo 'successful push to GitHub'