name: Deploy next 13 app
on:
    push:
        branches: [main, develop]
    # pull_request:
    #     branches: [main, develop]

jobs:
    build:
        runs-on: [ubuntu-latest]
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Install dependencies
              run: yarn

            - name: Perform build
              run: yarn build

    lint:
        runs-on: [ubuntu-latest]
        needs: build
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Install dependencies
              run: yarn

            - name: Perform lint
              run: yarn lint
